#! /usr/bin/ash

mkdir -p dev
mkdir -p proc
mkdir -p run
mkdir -p sysroot
mkdir -p sys

# Mount the /proc and /sys filesystems.
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
# /run directory would be moved to new root after switch_root,
# due to ostree-prepare-root need create booted file under /run.
mount -t tmpfs -o rw,nosuid,nodev,mode=755 tmpfs /run

rescue_shell() {
    echo "Something went wrong. Dropping to a shell."
    exec ash
}

# enable lvm VG
echo "make lvm group"
lvm vgscan --mknodes
lvm lvchange -a ly atomicos/root
lvm vgscan --mknodes

mount /dev/mapper/atomicos-root /sysroot

/usr/lib/ostree/ostree-prepare-root /sysroot || rescue_shell

umount /dev /proc /sys
echo "switch to rootfs"
exec switch_root /sysroot /sbin/init || rescue_shell
